APP_TITLE    := The Dark Knight Rises
APP_AUTHOR   := Gameloft (the game); Switch wrapper on android32
APP_VERSION  := 0.1.0
TARGET       := tdkr_nx
PORT_PAYLOAD := tdkr_nx

TOPDIR ?= $(CURDIR)
A32    ?= $(TOPDIR)/../runtime
include $(A32)/launcher/launcher.mk
